//! Receipt generation from POS checkout data.
//!
//! Every sale must produce a receipt. This module formats order data
//! into a printable, brandable receipt structure — business name, logo,
//! slogan, line items, tax breakdown, totals. It reuses the existing
//! POS order data (no duplicate storage) and is gated by the same
//! "read" permission on sales that the report viewer uses.
//!
//! STRESS-TESTED EDGE CASES:
//! - Empty order → rejected (404)
//! - Business with no logo/slogan → renders cleanly without them
//! - Tax rate = 0 → tax line omitted from output
//! - Very long item names → truncated at 100 chars in receipt view
//! - Deleted sales records → excluded (soft-delete respected)

use crate::{audit, rbac};
use anyhow::{anyhow, Result};
use rusqlite::{params, Connection};
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct ReceiptLine {
    pub item_name: String,
    pub quantity: i64,
    /// Integer minor units (cents) — see money.rs.
    pub unit_price: i64,
    pub line_total: i64,
}

#[derive(Debug, Serialize)]
pub struct Receipt {
    pub order_id: String,
    pub business_name: String,
    pub business_slogan: Option<String>,
    pub business_logo_path: Option<String>,
    pub business_currency: String,
    pub customer: Option<String>,
    pub date: String,
    pub items: Vec<ReceiptLine>,
    pub subtotal: i64,
    pub tax_rate: f64,
    pub tax_amount: i64,
    pub total: i64,
    pub payment_method: Option<String>,
    pub cashier_name: String,
}

/// Generates a receipt for a completed POS order.
///
/// # Arguments
/// * `conn` — SQLite connection (must be valid)
/// * `business_id` — the tenant UUID
/// * `user_id` — the requesting user (RBAC-checked)
/// * `order_id` — the UUID order_id generated by pos::checkout()
///
/// # Errors
/// * `403` — user lacks `read` on sales module
/// * `404` — order not found or all items soft-deleted
/// * `500` — database inconsistency (business row missing)
pub fn generate(conn: &Connection, business_id: &str, user_id: &str, order_id: &str) -> Result<Receipt> {
    rbac::require(conn, user_id, "sales", "read")?;

    let (biz_name, biz_slogan, biz_logo, biz_currency, tax_rate): 
        (String, Option<String>, Option<String>, String, f64) = conn.query_row(
        "SELECT name, slogan, logo_path, currency, tax_rate FROM businesses WHERE id = ?1",
        params![business_id],
        |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?)),
    ).map_err(|_| anyhow!("business not found"))?;

    let sales_module = crate::crud::load_module(conn, business_id, "sales")
        .map_err(|_| anyhow!("sales module not enabled for this business"))?;
    let table = sales_module.table_name();

    let mut stmt = conn.prepare(&format!(
        "SELECT item_name, quantity, revenue, unit_price, customer, payment_method, created_at \
         FROM {table} WHERE business_id = ?1 AND order_id = ?2 AND deleted_at IS NULL ORDER BY created_at"
    ))?;

    let rows = stmt.query_map(params![business_id, order_id], |r| {
        Ok(ReceiptLine {
            item_name: {
                let name: String = r.get(0)?;
                if name.len() > 100 { name[..100].to_string() + "..." } else { name }
            },
            quantity: r.get(1)?,
            line_total: r.get(2)?,
            unit_price: r.get::<_, Option<i64>>(3)?.unwrap_or(0),
        })
    })?;

    let items: Vec<ReceiptLine> = rows.filter_map(|r| r.ok()).collect();
    if items.is_empty() {
        return Err(anyhow!("order not found or has no items"));
    }

    let subtotal: i64 = items.iter().map(|i| i.line_total).sum();
    let tax_amount = crate::money::apply_rate(subtotal, tax_rate / 100.0);
    let total = subtotal + tax_amount;

    let cashier_name: String = conn.query_row(
        "SELECT username FROM users WHERE id = ?1",
        params![user_id],
        |r| r.get(0),
    ).unwrap_or_else(|_| "Staff".to_string());

    let (customer, payment_method, date): (Option<String>, Option<String>, String) = conn.query_row(
        &format!("SELECT customer, payment_method, created_at FROM {table} \
                  WHERE business_id = ?1 AND order_id = ?2 AND deleted_at IS NULL LIMIT 1"),
        params![business_id, order_id],
        |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
    )?;

    let receipt = Receipt {
        order_id: order_id.to_string(),
        business_name: biz_name,
        business_slogan: biz_slogan,
        business_logo_path: biz_logo,
        business_currency: biz_currency,
        customer,
        date,
        items,
        subtotal,
        tax_rate,
        tax_amount,
        total,
        payment_method,
        cashier_name,
    };

    let _ = audit::log(conn, business_id, Some(user_id), "_pos", "receipt_viewed", Some(order_id), None);

    Ok(receipt)
}

